spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/song-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${POSTGRES_DEFAULT_PASSWORD}
  profiles:
    active: prod

server:
  port: 8082
